<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.2" />
    <PackageReference Include="ChoETL" Version="1.2.1.70" />
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Ofgem.LAF.SharedLibrary" Version="1.0.225" />

    <PackageReference Include="Serilog" Version="4.2.0" />

    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ofgem.API.LAF.LocalAuthorityManagement.Application\Ofgem.API.LAF.LocalAuthorityManagement.Application.csproj" />
  </ItemGroup>

</Project>
